services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${EMBEDDING_STORE_DATABASE:-embeddings}
      POSTGRES_USER: ${EMBEDDING_STORE_USER:-postgres}
      POSTGRES_PASSWORD: ${EMBEDDING_STORE_PASSWORD:-postgres}
    restart: always
    ports:
      - "${EMBEDDING_STORE_PORT:-5432}:5432"
    volumes:
      - ./docker/volume/maven-pgvector:/var/lib/postgresql/data
