embeddingstore.batchSize=5

langchain4j.ollama.chat-model.base-url=http://127.0.0.1:11434
langchain4j.ollama.chat-model.model-name=llama3
logging.level.dev.langchain4j=TRACE
logging.level.dev.ai4j.openai4j=DEBUG
logging.level.net.aschemann=DEBUG